//Errores en funciones asincronas


/* 
async function obtenerDatos() {
    try {
        let respuesta = await fetch("https://api.example.com/datos");
        let datos = await respuesta.json();
        console.log(datos);
    } catch (error) {
        console.error("Se produjo un error al obtener los datos:", error);
    }
}

obtenerDatos();

*/


